Interactive list :feature
Haadiiii/todo-list pull request #3
Opened 2022-08-12 23:35 UTC by Haadiiii

## Interactive LIST TODO Implementation ⏬ 👍 

In this project we : 

- Added Webpack. 👍 
- Added `index.js` file 👍 
- Added Modules js for `js` file 👍 
- Added `Array of Objects` for lists 👍 
- ADDED (`ADD, REMOVE, EDIT, CLEAR`) todo Items 👍 .
- Implement `ES6` 👍 
- Added `index.CSS` style. 👍 
- Added `index.Html` File. 👍 
- Resolved `Linters` 👍 
- Added `README.md` FIle 👍 

😄

2022-08-12 23:58 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 @Haadiiii  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Highlights 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
___


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-08-12 23:58 UTC, ahmetbozaci commented on .eslintrc.json
> +    "no-multi-spaces": "off",
- [ ] You shouldn't change the linter settings. Kindly open it and if giving an error please fix it.

2022-08-12 23:58 UTC, ahmetbozaci commented on src/modules/showlist.js
> +      }
- [ ] Completed status should change when clicking on the checkbox. Kindly fix it. [Requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m2_interactive_list.md#:~:text=Update%20items%20object%27s%20value%20for%20completed%20key%20upon%20user%20actions.)

![image](https://user-images.githubusercontent.com/38635158/184458074-76ed6b3a-71a5-47ef-aea5-14a4834c3756.png)

2022-08-13 00:06 UTC, Haadiiii commented on src/modules/showlist.js
> +      }
@ahmetbozaci hi,
yeah itll become when you select all the items the checkbox will be checked automatically and the status would changed to true.. try it

2022-08-13 00:07 UTC, Haadiiii commented on src/modules/showlist.js
> +      }
@ahmetbozaci select any of the entire item by  right clicking... then check 👍

2022-08-13 00:09 UTC, Haadiiii commented on .eslintrc.json
> +    "no-multi-spaces": "off",
@ahmetbozaci 
oh yeah i don't know why these were appearing because there were no empty lines that's why at last I did this, I had no choice. 😅

2022-08-13 00:15 UTC, Haadiiii commented on src/modules/showlist.js
> +      }
@ahmetbozaci i already mention there that how to select items...

2022-08-13 00:32 UTC, ahmetbozaci commented on src/modules/showlist.js
> +      }
> @ahmetbozaci i already mention there that how to select items...

But ı already select an item with a click on the checkbox if ı have to do a right click again to change status don't you think it is not good for the user? The user can think do I have to do a double job just to change the status?

2022-08-13 00:37 UTC, ahmetbozaci commented on .eslintrc.json
> +    "no-multi-spaces": "off",
@Haadiiii You can check the error in google. I am sure you can find a solution.

2022-08-13 00:44 UTC, Haadiiii commented on src/modules/showlist.js
> +      }
@ahmetbozaci 
no i think you didn't understand, am saying when you right on items not checkbox the itmes would be selected also the checkbox.. 
yeah you are right user dont have double jobe thats why i clearly mentioned there..

2022-08-13 00:47 UTC, BenMukebo requested changes
Hi @Haadiiii, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


- [OPTIONAL] It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser.. This includes `git clone URL` , `cd project_name`,  `npm install`, `npm start`, etc 🙃 

- please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.

- [OPTIONAL] I would also recommend adding the issue link in the contributing sections actually  I get another page: 

```
## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).
```

- [OPTIONAL ] When I click the link to the `MIT.md` file that you added, I get this 404 `error`: 

#### The reason for this is that there is no `MIT.md` file in the root directory of this project. Kindly attach the file. 👍

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-13 00:47 UTC, BenMukebo commented on .eslintrc.json
> +    "no-multi-spaces": "off",
- [ ] As requested by the previous reviewer 👇🏻 Linter file should not be modified, Kindly address this issue 👍🏻 
> 
> - [ ] You shouldn't change the linter settings. Kindly open it and if giving an error please fix it.
>

2022-08-13 00:47 UTC, BenMukebo commented on src/modules/Elements.js
>  export const dataa = document.getElementById("items");
- [OPTIONAL] According to the Project requirements, you should create one new JavaScript file imported as a module and which will contain methods related to the status updates (completed: true / false). Kindly make this ✍🏻

2022-08-13 00:47 UTC, BenMukebo commented on src/modules/showlist.js
> +      }
- [ ] As requested by the previous reviewer, Please make sure you have a 1. Event listener on the checkbox (`change`). 2. The task object's values for `completed` should be updated upon user actions. and  3. The updated array of items is stored in local storage, so the user gets the correct list values after the page reloads. Make sure to reload the page to test if the array is stored. Kindly address this 👍🏻

2022-08-13 01:10 UTC, ahmetbozaci commented on src/modules/showlist.js
> +      }
@Haadiiii I test it. Status is changing when right-clicking on the text. But it is kinda unusual to select the item on the webpage. You already have a checkbox next to the text you can use it.

2022-08-13 11:34 UTC, Haadiiii commented on .eslintrc.json
> +    "no-multi-spaces": "off",
@BenMukebo hey,
yeah i fied it 😄 .

2022-08-13 11:35 UTC, Haadiiii commented on src/modules/Elements.js
>  export const dataa = document.getElementById("items");
okay but i cant make it cause there is a map action there where i created many items within there so that's why, next time ill in another way 👍  thanks for the suggestion 😄

2022-08-13 11:35 UTC, Haadiiii commented on src/modules/showlist.js
> +      }
@BenMukebo yeah when you refresh the local storage it'll appear  👍

2022-08-13 11:37 UTC, Haadiiii commented on src/modules/showlist.js
> +      }
@ahmetbozaci hey,
 yeah thanks for the i did the way you wanted, yeah it took me long that's why i argue you last night 😄 sorry for that ,, and i did the same you wanted 👍

2022-08-13 11:38 UTC, Haadiiii commented on .eslintrc.json
> +    "no-multi-spaces": "off",
@ahmetbozaci 
ahan yeah 👍  i got it .. thanks

2022-08-13 11:52 UTC, Ismailco approved these changes
### Hi @Haadiiii, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-13 11:52 UTC, Ismailco commented on src/modules/showlist.js
>  let task = [];
- [ ] [OPTIONAL] Kindly make sure to start index from 1, not 0, so the list items have the correct indexing

2022-08-13 12:07 UTC, merged